CREATE DATABASE panorama;

USE PANORAMA;

CREATE TABLE Usuario (
Id INT IDENTITY(1,1),
Nome VARCHAR(100),
Senha BINARY(60),
PRIMARY KEY(Id)
);

CREATE TABLE Perfil (
Id INT IDENTITY(1,1),
IdUsuario INT,
Nome VARCHAR(100),
Foto VARCHAR(200),
Email VARCHAR(100),
Descricao VARCHAR(300),
PRIMARY KEY(Id),
FOREIGN KEY (IdUsuario) REFERENCES Usuario(Id)
);

CREATE TABLE Grupo (
Id INT IDENTITY(1,1),
IdPerfil INT,
Nome VARCHAR(100),
Descricao VARCHAR(300),
PRIMARY KEY(Id)
);

CREATE TABLE Tarefa (
Id INT IDENTITY(1,1),
IdGrupo INT,
Nome VARCHAR(100),
InicioTarefa DATETIME,
FimTarefa DATETIME,
Descricao VARCHAR(300),
DIFICULDADE TINYINT,
CONCLUIDO BIT,
PRIMARY KEY(Id),
FOREIGN KEY (IdGrupo) REFERENCES Grupo(Id)
);

CREATE TABLE Atributo (
Id INT IDENTITY(1,1),
Nome VARCHAR(100),
Icone VARCHAR(100),
Xp INT,
PRIMARY KEY(Id)
);

CREATE TABLE TarefaAtributo (
Id INT IDENTITY(1,1),
IdTarefa INT,
IdAtributo INT,
PRIMARY KEY(Id),
FOREIGN KEY (IdTarefa) REFERENCES Tarefa(Id),
FOREIGN KEY (IdAtributo) REFERENCES Atributo(Id)
);